resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storeo
images:
- name: minhdtb/storeo-shop
  newTag: e6782f7adf280c86dbac6d030ac8a68abcbf7f63
